name: DiscordAuthentication
main: com.johnymuffin.beta.discordauth.DiscordAuthentication
author: JohnyMuffin
version: 1.1.0
depend: [DiscordCore, UUIDCore]
commands:
  discordauth:
    description: Basic DiscordAuth commands
    usage: /<command>